function [run_ID, fname] = create_log(var_names, varargin)
%CREATE_LOG  Generate and log pipeline run information to an executable .m file
%
%   Usage:
%       [run_ID, fname] = create_log(var_names, 'Name', Value, ...)
%
%   Inputs:
%       var_names : cell of char - names of caller-workspace variables to log -- required
%
%   Name-Value Pairs:
%       'run_ID'     : char - unique identifier for the run (default: '' -- autogenerate)
%       'ID_len'     : integer - length of autogenerated unique identifier (default: 7)
%       'fname'      : char - output log filename (default: '' -- autogenerate from prefix/ID/time)
%       'run_prefix' : char - prefix used when autogenerating fname (default: 'runlog')
%       'file_path'  : char - directory to write the log file into (default: '')
%       'write_file' : logical - whether to write the log to disk (default: true)
%       'verbose'    : logical - whether to also echo the log to the command window (default: true)
%
%   Outputs:
%       run_ID : char - unique identifier for this run
%       fname  : char - filename of the written log
%
%   Example:
%       struct1.f1 = 'asdf';
%       struct1.f2 = 23;
%       struct1.f3 = [1 2 3 4 9454];
%
%       struct2.f1 = {[1 23 4], 'cheese', 343, 'a'};
%       struct2.f2 = 'this is a struct';
%       struct2.f3 = 'goat';
%
%       scalar_var = 3;
%       vect_var = [6 34 2 5 3];
%       mat_var = randn(5);
%       char_var = 'qwerty';
%       log_var = false;
%       cell_var = {'a', 234, [6 5 3]};
%
%       varnames = {'scalar_var','vect_var','mat_var','char_var','log_var','cell_var','struct1','struct2'};
%       create_log(varnames, 'run_prefix', 'myrun', 'ID_len', 7);
%
%   See also: generate_run_log, struct2codestr
%
%   ∿∿∿  Prerau Laboratory MATLAB Codebase · sleepEEG.org  ∿∿∿

% Generate example data
if nargin == 0
    struct1.f1 = 'asdf';
    struct1.f2 = 23;
    struct1.f3 = [1 2 3 4 9454];

    struct2.f1 = {[1 23 4], 'cheese', 343, 'a'};
    struct2.f2 = 'this is a struct';
    struct2.f3 = 'goat';
    
    scalar_var = 3;
    vect_var = [6 34 2 5 3];
    mat_var = randn(5);
    char_var = 'qwerty';
    cell_var = {'a', 234, [6 5 3]};

    varnames = {'scalar_var','vect_var','mat_var', 'char_var','cell_var',  'struct1', 'struct2'};

    create_log(varnames, 'run_prefix', 'myrun', 'ID_len', 7);
    return;
end

% Create an input parser
p = inputParser;
p.CaseSensitive = false;

% Add parameters to the input parser
addParameter(p, 'run_ID', '', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'ID_len', 7, @(x) validateattributes(x, {'numeric'}, {'scalar', 'positive', 'integer'}));
addParameter(p, 'fname', '', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'run_prefix','runlog', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'file_path', '', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'write_file', true, @(x) validateattributes(x, {'logical'}, {'scalar'}));
addParameter(p, 'verbose', true, @(x) validateattributes(x, {'logical'}, {'scalar'}));

% Parse inputs
parse(p,varargin{:});

% Retrieve parsed inputs
run_prefix = p.Results.run_prefix;
run_ID = p.Results.run_ID;
fname = p.Results.fname;
file_path = p.Results.file_path;
write_file = p.Results.write_file;
verbose = p.Results.verbose;
ID_len = p.Results.ID_len;

% Generate Unique ID
if isempty(run_ID)
    idGEN =  java.util.UUID.randomUUID;
    run_ID = char(idGEN.toString);
    run_ID = run_ID(1:ID_len);
    %If the last value is an underscore, replace with a valid character
    if strcmp(run_ID(end),'_')
        randvalid = char([randi([65, 90]) randi([97, 122])  randi([48, 57])]);
        run_ID(end) = randvalid(randi(3));
    end
end

% Log start time
dtime = datetime;
dtime.Format = 'yyyyMMdd_HHmmss';
run_start = char(dtime);

if isempty(fname)
    % Generate file name
    fname = [run_prefix '_' run_ID '_' run_start '.m'];
end

% Force fname to be a valid name
fname = strrep(fname,' ','_');
fname = strrep(fname,'-','_');
fname = strrep(fname,':','');

% Check for valid name
assert(is_valid_matlab_filename(fname),...
    ['Must be valid filename: Under 63 chars, start with a letter,' ...
    'contain only letters, digits, and underscores, no reserved keywords']);

%Open up the file
if write_file
    fid = fopen(fullfile(file_path,fname), 'w');
    assert(fid ~= -1, ['Could not open file for writing: ' fullfile(file_path,fname)]);
    cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
end

%% WRITE ID
if verbose
    disp(['%% ' fname])
    disp(' ')
    disp('% Unique ID')
    disp(['run_ID = ' run_ID ''';'])
end

if write_file
    fprintf(fid, '%%%% %s\n\n', fname);
    fprintf(fid, '%% Unique ID\n');
    fprintf(fid, 'run_ID = ''%s'';\n', run_ID);
end

%% WRITE TIME
if verbose
    disp('% Start Time')
    disp(['run_start = ' run_start ''';'])
    disp(' ');
end

if write_file
    fprintf(fid, '%% Start Time\n');
    fprintf(fid, 'run_start = ''%s'';\n\n', run_start);
end

%% WRITE ALL VARIABLES
for ii = 1:length(var_names)
    var_name = var_names{ii};
    if evalin('caller',['exist(''' var_name ''',''var'');'])
        if evalin('caller',['isstruct(' var_name ');'])
            % Generate Option Structure
            if verbose
                disp(['% Generate ' var_name])
            end
            if write_file
                fprintf(fid, '%% Generate %s\n', var_name);
            end

            struct_code = evalin('caller',['struct2codestr(' var_name,', ''' var_name ''')']);
            if verbose
                disp(struct_code)
            end

            if write_file
                fprintf(fid, '%s\n', struct_code);
            end
        else
            %% WRITE VARS
            var_str = value2str(evalin('caller',var_name));
            % Generate Option Structure
            if verbose
                disp(['% ' var_name])
                disp([var_name ' = ' var_str ';'])
                disp(' ');
            end

            if write_file
                fprintf(fid, '%% %s\n', var_name);
                fprintf(fid, '%s = %s;\n\n', var_name, var_str);
            end
        end
    end
end


%Check for valid filename
function valid = is_valid_matlab_filename(filename)
% Check if the filename is empty or exceeds 63 characters
if isempty(filename) || length(filename) > 63
    valid = false;
    return;
end

% Check if the filename starts with a letter
if ~isletter(filename(1))
    valid = false;
    return;
end

% Check if the filename contains only letters, digits, and underscores
if ~isvarname(filename(1:end-2))
    valid = false;
    return;
end

% Check if the filename is a reserved MATLAB keyword
if iskeyword(filename)
    valid = false;
    return;
end

% Check if the filename ends with a period or space
if endsWith(filename, '.') || endsWith(filename, ' ')
    valid = false;
    return;
end

% If all checks pass, the filename is valid
valid = true;
