%GENERATE_RUN_LOG Generate and log information for a pipeline run
%
%   Usage:
%       [run_ID, fname] = generate_run_log2(structs, struct_names, vars, var_names, varargin)
%
%   Input:
%       structs: cell array - containing structures -- required
%       struct_names: cell array - names of the structures -- required
%       vars: cell array - containing variables -- required
%       var_names: cell array - names of the variables -- required
%       run_ID: char - unique identifier for the run (Default: Autogenerated ID)
%       fname: char - file name to save the log (Default: Autogenerated from ID and date/time)
%       file_path: char - path for filename (Default: empty)
%       write_file: logical - flag to indicate whether to write the log to a file (Default: true)
%       verbose: logical - flag to indicate whether to display verbose output (Default: true)
%       ID_len: numeric - length of the unique identifier (Default: 7)
%
%   Output:
%       run_ID: char - unique identifier for the run
%       fname: char - file name to save the log
%
%   Example:
%       % Define structures
%       struct_names = {'opt_struct1', 'opt_struct2'};
%
%       opt_struct1.f1 = 'asdf';
%       opt_struct1.f2 = 23;
%       opt_struct1.f3 = [1 2 3 4 9454];
%
%       opt_struct2.f1 = {[1 23 4], 'cheese', 343, 'a'};
%       opt_struct2.f2 = 'this is a struct';
%       opt_struct2.f3 = 'goat';
%
%       structs{1} = opt_struct1;
%       structs{2} = opt_struct2;
%
%       % Define variables
%       varnames = {'var1','var2','var3','var4'};
%       vars = {3, [6 34 2 5 3], 'qwerty', {'a', 234, [6 5 3]}};
%
%       generate_run_log(structs, struct_names, vars, varnames, 'run_ID', 'myrun', 'ID_len', 30);
%
%   Copyright 2024 Michael J. Prerau Laboratory - http://www.sleepEEG.org
%   **********************************************************************

function [run_ID, fname] = generate_run_log(structs, struct_names, vars, var_names, varargin)
% Generate example data
if nargin == 0
    %Run prefix
    struct_names = {'opt_struct1', 'opt_struct2'};

    opt_struct1.f1 = 'asdf';
    opt_struct1.f2 = 23;
    opt_struct1.f3 = [1 2 3 4 9454];

    opt_struct2.f1 = {[1 23 4], 'cheese', 343, 'a'};
    opt_struct2.f2 = 'this is a struct';
    opt_struct2.f3 = 'goat';

    structs{1} = opt_struct1;
    structs{2} = opt_struct2;

    varnames = {'var1','var2','var3','var4'};
    vars = {3, [6 34 2 5 3], 'qwerty', {'a', 234, [6 5 3]}};

    generate_run_log(structs, struct_names, vars, varnames, 'run_prefix', 'myrun', 'ID_len', 7);
    return;
end

% Create an input parser
p = inputParser;
p.CaseSensitive = false;

% Add parameters to the input parser
addParameter(p, 'run_ID', '', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'ID_len', 7, @(x) validateattributes(x, {'numeric'}, {'scalar', 'positive', 'integer'}));
addParameter(p, 'fname', '', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'run_prefix','runlog', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'file_path', '', @(x) validateattributes(x, {'char'}, {'row'}));
addParameter(p, 'write_file', true, @(x) validateattributes(x, {'logical'}, {'scalar'}));
addParameter(p, 'verbose', true, @(x) validateattributes(x, {'logical'}, {'scalar'}));

% Parse inputs
parse(p,varargin{:});

% Retrieve parsed inputs
run_prefix = p.Results.run_prefix;
run_ID = p.Results.run_ID;
fname = p.Results.fname;
file_path = p.Results.file_path;
write_file = p.Results.write_file;
verbose = p.Results.verbose;
ID_len = p.Results.ID_len;

assert(~(isempty(structs) && isempty(vars)),'Must have either structs or vars');

% Generate Unique ID
if isempty(run_ID)
    idGEN =  java.util.UUID.randomUUID;
    run_ID = char(idGEN.toString);
    run_ID = run_ID(1:ID_len);
    %If the last value is an underscore, replace with a valid character
    if strcmp(run_ID(end),'_')
        randvalid = char([randi([65, 90]) randi([97, 122])  randi([48, 57])]);
        run_ID(end) = randvalid(randi(3));
    end
end

% Log start time
dtime = datetime;
dtime.Format = 'yyyyMMdd_HHmmss';
run_start = char(dtime);

if isempty(fname)
    % Generate file name
    fname = [run_prefix '_' run_ID '_' run_start '.m'];
end

% Force fname to be a valid name
fname = strrep(fname,' ','_');
fname = strrep(fname,'-','_');
fname = strrep(fname,':','');

% Check for valid name
assert(is_valid_matlab_filename(fname),...
    ['Must be valid filename: Under 63 chars, start with a letter,' ...
    'contain only letters, digits, and underscores, no reserved keywords']);

%Open up the file
if write_file
    fid = fopen(fullfile(file_path,fname), 'w');
end

%% WRITE ID
if verbose
    disp(['%% ' fname])
    disp(' ')
    disp('% Unique ID')
    disp(['run_ID = ' run_ID ''';'])
end

if write_file
    fprintf(fid, '%%%% %s\n\n', fname);
    fprintf(fid, '%% Unique ID\n');
    fprintf(fid, 'run_ID = ''%s'';\n', run_ID);
end

%% WRITE TIME
if verbose
    disp('% Start Time')
    disp(['run_start = ' run_start ''';'])
    disp(' ');
end

if write_file
    fprintf(fid, '%% Start Time\n');
    fprintf(fid, 'run_start = ''%s'';\n\n', run_start);
end

%% WRITE STRUCTS
if ~isempty(structs)
    % Generate structure code
    for ii = 1:length(structs)
        struct_name = struct_names{ii};
        % Generate Option Structure
        if verbose
            disp(['% Generate ' struct_name])
        end
        if write_file
            fprintf(fid, '%% Generate %s\n', struct_name);
        end

        struct_code = struct2codestr(structs{ii}, struct_name);
        if verbose
            disp(struct_code)
        end

        if write_file
            fprintf(fid, '%s\n', struct_code);
        end
    end
end

%% WRITE VARS
if ~isempty(vars)
    % Generate variable code
    for ii = 1:length(vars)
        var_name = var_names{ii};
        var_str = value2str(vars{ii});
        % Generate Option Structure
        if verbose
            disp(['% ' var_name])
            disp([var_name ' = ' var_str ';'])
            disp(' ');
        end

        if write_file
            fprintf(fid, '%% %s\n', var_name);
            fprintf(fid, '%s = %s;\n\n', var_name, var_str);
        end
    end
end

% Close file
if write_file
    fclose(fid);
end

%Check for valid filename
function valid = is_valid_matlab_filename(filename)
% Check if the filename is empty or exceeds 63 characters
if isempty(filename) || length(filename) > 63
    valid = false;
    return;
end

% Check if the filename starts with a letter
if ~isletter(filename(1))
    valid = false;
    return;
end

% Check if the filename contains only letters, digits, and underscores
if ~isvarname(filename(1:end-2))
    valid = false;
    return;
end

% Check if the filename is a reserved MATLAB keyword
if iskeyword(filename)
    valid = false;
    return;
end

% Check if the filename ends with a period or space
if endsWith(filename, '.') || endsWith(filename, ' ')
    valid = false;
    return;
end

% If all checks pass, the filename is valid
valid = true;
