function vmrk_table = import_vmrk(filename, dataLines)
%import_vmrk Import data from a text file
%  vmrk_table = import_vmrk(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  vmrk_table = import_vmrk(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  vmrk_table = import_vmrk("/data/preraugp/archive/SZEEG/Eszopiclone/legacy files/vmrks/ez_4A.vmrk", [13, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Jun-2022 09:43:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [13, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", "="];

% Specify column names and types
opts.VariableNames = ["Var1", "EventType", "Description", "TimeStamp", "Var5", "Var6", "Var7"];
opts.SelectedVariableNames = ["EventType", "Description", "TimeStamp"];
opts.VariableTypes = ["string", "categorical", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var5", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "EventType", "Var5", "Var6", "Var7"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Description", "TrimNonNumeric", true);
opts = setvaropts(opts, "Description", "ThousandsSeparator", ",");
opts.VariableTypes = ["string", "string", "string", "double", "string", "string", "string"];

% Import the data
vmrk_table = readtable(filename, opts);

end