function result = isIOdatatype(typestr)
%ISIODATATYPE  Check whether a MATLAB type string names a native binary I/O data type
%
%   Usage:
%       result = isIOdatatype(typestr)
%
%   Inputs:
%       typestr : char - candidate type name (e.g., 'double', 'uint16', 'int8') -- required
%
%   Outputs:
%       result : logical - true if the type can be read/written with fread/fwrite
%                without byte-stream serialization
%
%   See also: bytestream_save, bytestream_load, MBFwrite
%
%   ∿∿∿  Prerau Laboratory MATLAB Codebase · sleepEEG.org  ∿∿∿

nativetypes = ...
    {'uint',...
    'uint8',...
    'uint16',...
    'uint32',...
    'uint64',...
    'uchar',...
    'unsigned char',...
    'ushort',...
    'ulong',...
    'int8',...
    'int16',...
    'int32',...
    'int64',...
    'integer*1',...
    'integer*2',...
    'integer*4',...
    'integer*8',...
    'schar',...
    'signed char',...
    'short',...
    'long',...
    'double',...
    'float',...
    'float32',...
    'float64',...
    'real*4',...
    'real*8',...
    'char'...
    'single'};

typestr = lower(typestr);
result = any(strcmpi(typestr, nativetypes)) || contains(typestr,'bit') || contains(typestr,'ubit');