%Checks to see if we need to convert to bytestream
function result = isIOdatatype(typestr)
nativetypes = ...
    {'uint',...
    'uint8',...
    'uint16',...
    'uint32',...
    'uint64',...
    'uchar',...
    'unsigned char',...
    'ushort',...
    'ulong',...
    'int8',...
    'int16',...
    'int32',...
    'int64',...
    'integer*1',...
    'integer*2',...
    'integer*4',...
    'integer*8',...
    'schar',...
    'signed char',...
    'short',...
    'long',...
    'double',...
    'float',...
    'float32',...
    'float64',...
    'real*4',...
    'real*8',...
    'char'...
    'single'};

typestr = lower(typestr);
result = any(strcmpi(typestr, nativetypes)) || contains(typestr,'bit') || contains(typestr,'ubit');